platform: linux/arm

pipeline:
  tests:
    image: registry.banana.pi:5000/f12-testing:arm
    commands:
      - autoreconf --install
      - ./configure
      - make check || (cat tests/test-suite.log && exit 1)
      - /usr/local/bin/bats --tap tests/functional.bats
