---
kind: "pipeline"
name: "default"

steps:
        - name: "pull submodules"
          image: "registry.kalehmann.de/testing/f12:latest"
          commands:
                - "git submodule update --init --recursive --remote"
        - name: "build"
          image: "registry.kalehmann.de/testing/f12:latest"
          commands:
                - "autoreconf --install"
                - "./configure --enable-beautify --enable-coverage"
                - "make CFLAGS='-Wall'"
          depends_on:
                - "pull submodules"
        - name: "style-check"
          image: "registry.kalehmann.de/testing/f12:latest"
          commands:
                - "make beautify"
                - "git diff --exit-code"
          depends_on:
                - "build"
        - name: "unit-tests"
          image: "registry.kalehmann.de/testing/f12:latest"
          commands:
                - "make check || (cat test-suite.log && exit 1)"
          depends_on:
                - "build"
          environment:
                GCOV_PREFIX: "/tmp/unit-tests"
        - name: "bats"
          image: "registry.kalehmann.de/testing/f12:latest"
          commands:
                - "/usr/local/bin/bats --tap tests/functional.bats"
          depends_on:
                - "unit-tests"
          environment:
                TMP_DIR: "/tmp/bats"
                VALGRIND: "1"
                VALGRIND_TAP: "valgrind.tap"
        - name: "coverage-report"
          image: "registry.kalehmann.de/testing/f12:latest"
          commands:
                - "make coverage-report"
          depends_on:
                - "bats"
        - name: "valgrind-log"
          image: "registry.kalehmann.de/testing/f12:latest"
          commands:
                - "cat valgrind.tap"
          depends_on:
                - "bats"
          when:
                status:
                        - "failure"
image_pull_secrets:
        - "dockerconfigjson"
...